### ISSUE TITLE
Could not find microscope image quality plugin in fiji

### ISSUE THREAD

**Issue by d5423197** [fiji/microscope-image-quality#9]
Hello there,

I could not find microscope image quality plugin in fiji. Is there any way to add that plugin in fiji?

Thanks,

**Comment by ctrueden** [comment]
@d5423197 Yes! Please enable the TensorFlow update site. Run _Help &rsaquo; Update..._, click the "Manage update sites" button, then check the "TensorFlow" box. (This is noted in the [installation instructions](https://imagej.net/plugins/microscope-focus-quality#installation), but easy to miss because it is so brief.)

**Comment by d5423197** [comment]
Thanks for your help. I have been trying to figure it out for a couple of hours. Now I feel like I am so silly..
